// swift-tools-version:5.9
// PLACEHOLDER manifest. The real one is generated by
// scripts/gen-package-swift.sh and pushed by the release workflow on the
// first tag (v*). Until a release exists the URLs/checksums below are dummies
// and `swift package resolve` will fail — that's expected.
//
// Consumers import the individual modules (Libavformat, Libavcodec, Libavutil,
// Libavfilter, Libswscale, Libswresample). The clang module map lives inside
// the libavutil xcframework and declares all six modules. The FFmpegSupport
// target carries the linker settings (zlib + VideoToolbox stack).
import PackageDescription

let package = Package(
    name: "StashyVideoEngine",
    platforms: [.iOS(.v15)],
    products: [
        .library(
            name: "FFmpeg",
            targets: [
                "avutil", "avcodec", "avformat",
                "avfilter", "swscale", "swresample",
                "FFmpegSupport",
            ]
        ),
    ],
    targets: [
        .binaryTarget(name: "avutil",     url: "https://github.com/nphil/stashy-videoengine/releases/download/v0.0.0/libavutil.xcframework.zip",     checksum: "0000000000000000000000000000000000000000000000000000000000000000"),
        .binaryTarget(name: "avcodec",    url: "https://github.com/nphil/stashy-videoengine/releases/download/v0.0.0/libavcodec.xcframework.zip",    checksum: "0000000000000000000000000000000000000000000000000000000000000000"),
        .binaryTarget(name: "avformat",   url: "https://github.com/nphil/stashy-videoengine/releases/download/v0.0.0/libavformat.xcframework.zip",   checksum: "0000000000000000000000000000000000000000000000000000000000000000"),
        .binaryTarget(name: "avfilter",   url: "https://github.com/nphil/stashy-videoengine/releases/download/v0.0.0/libavfilter.xcframework.zip",   checksum: "0000000000000000000000000000000000000000000000000000000000000000"),
        .binaryTarget(name: "swscale",    url: "https://github.com/nphil/stashy-videoengine/releases/download/v0.0.0/libswscale.xcframework.zip",    checksum: "0000000000000000000000000000000000000000000000000000000000000000"),
        .binaryTarget(name: "swresample", url: "https://github.com/nphil/stashy-videoengine/releases/download/v0.0.0/libswresample.xcframework.zip", checksum: "0000000000000000000000000000000000000000000000000000000000000000"),
        .target(
            name: "FFmpegSupport",
            dependencies: [
                "avutil", "avcodec", "avformat",
                "avfilter", "swscale", "swresample",
            ],
            linkerSettings: [
                .linkedLibrary("z"),
                .linkedFramework("VideoToolbox"),
                .linkedFramework("CoreMedia"),
                .linkedFramework("CoreVideo"),
                .linkedFramework("CoreFoundation"),
            ]
        ),
    ]
)
