// swift-tools-version:5.9
// AUTO-GENERATED by scripts/gen-package-swift.sh for release v1.0.0.
// Do not edit by hand — re-run the release workflow to regenerate.
//
// Consumers import the individual modules (Libavformat, Libavcodec, Libavutil,
// Libavfilter, Libswscale, Libswresample). The clang module map lives inside
// the libavutil xcframework and declares all six modules.
import PackageDescription

let package = Package(
    name: "StashyVideoEngine",
    platforms: [.iOS(.v15)],
    products: [
        .library(
            name: "FFmpeg",
            targets: [
                "avutil", "avcodec", "avformat",
                "avfilter", "swscale", "swresample",
                "FFmpegSupport",
            ]
        ),
    ],
    targets: [
        .binaryTarget(
            name: "avutil",
            url: "https://github.com/nphil/stashy-videoengine/releases/download/v1.0.0/libavutil.xcframework.zip",
            checksum: "2581897e648bd2c2bcf059acee0903df35468385e051cb42c5f5dd0fed8bbb82"
        ),
        .binaryTarget(
            name: "avcodec",
            url: "https://github.com/nphil/stashy-videoengine/releases/download/v1.0.0/libavcodec.xcframework.zip",
            checksum: "2bc9a3fba29a360e97bb0507f82e1325c67cc5ca658f96e1efb3c2d195070308"
        ),
        .binaryTarget(
            name: "avformat",
            url: "https://github.com/nphil/stashy-videoengine/releases/download/v1.0.0/libavformat.xcframework.zip",
            checksum: "d03d13c35e3cd2da9af11d263ebd19c245d8e0931eaa7b9e791fdf8a8f211738"
        ),
        .binaryTarget(
            name: "avfilter",
            url: "https://github.com/nphil/stashy-videoengine/releases/download/v1.0.0/libavfilter.xcframework.zip",
            checksum: "30e4f219e47e91cc8f997ce1d670dcc2992a358136a510742c1d0bceac7a83bc"
        ),
        .binaryTarget(
            name: "swscale",
            url: "https://github.com/nphil/stashy-videoengine/releases/download/v1.0.0/libswscale.xcframework.zip",
            checksum: "3fed9bd95dba8b5dd25315d0a3583f5103da406b8e6bf7609dc1b65358fd37d6"
        ),
        .binaryTarget(
            name: "swresample",
            url: "https://github.com/nphil/stashy-videoengine/releases/download/v1.0.0/libswresample.xcframework.zip",
            checksum: "5d870043ebdcd51ef366cf74089748864b51d68964f7508276720149e3757a09"
        ),
        .target(
            name: "FFmpegSupport",
            dependencies: [
                "avutil", "avcodec", "avformat",
                "avfilter", "swscale", "swresample",
            ],
            linkerSettings: [
                .linkedLibrary("z"),
                .linkedFramework("VideoToolbox"),
                .linkedFramework("CoreMedia"),
                .linkedFramework("CoreVideo"),
                .linkedFramework("CoreFoundation"),
            ]
        ),
    ]
)
