// swift-tools-version:5.9
// AUTO-GENERATED by scripts/gen-package-swift.sh for release v1.1.0.
// Do not edit by hand — re-run the release workflow to regenerate.
//
// Consumers import the individual modules (Libavformat, Libavcodec, Libavutil,
// Libavfilter, Libswscale, Libswresample). The clang module map lives inside
// the libavutil xcframework and declares all six modules.
import PackageDescription

let package = Package(
    name: "StashyVideoEngine",
    platforms: [.iOS(.v16)],
    products: [
        .library(
            name: "FFmpeg",
            targets: [
                "avutil", "avcodec", "avformat",
                "avfilter", "swscale", "swresample",
                "FFmpegSupport",
            ]
        ),
    ],
    targets: [
        .binaryTarget(
            name: "avutil",
            url: "https://github.com/nphil/stashy-videoengine/releases/download/v1.1.0/libavutil.xcframework.zip",
            checksum: "d48e2c1e69ac38cdeaf48740ee7a628fda7b7d591ff467a216c73e6a78cfefd4"
        ),
        .binaryTarget(
            name: "avcodec",
            url: "https://github.com/nphil/stashy-videoengine/releases/download/v1.1.0/libavcodec.xcframework.zip",
            checksum: "532bcef71c5ee420db725b5babb32aa6ef50691cac6a1c5efe5c2073f43d7228"
        ),
        .binaryTarget(
            name: "avformat",
            url: "https://github.com/nphil/stashy-videoengine/releases/download/v1.1.0/libavformat.xcframework.zip",
            checksum: "2db9f5ac9a0f014dfef1de14fe97a18096b53491250d5469c932d829f70b78e3"
        ),
        .binaryTarget(
            name: "avfilter",
            url: "https://github.com/nphil/stashy-videoengine/releases/download/v1.1.0/libavfilter.xcframework.zip",
            checksum: "6b6868763168142601fcf73126124f71e9a70ed8d24114b3d445c26e98abb79e"
        ),
        .binaryTarget(
            name: "swscale",
            url: "https://github.com/nphil/stashy-videoengine/releases/download/v1.1.0/libswscale.xcframework.zip",
            checksum: "799daafb979edbe09394706c53c11d0853797d059c2c1946c60ddb0ae80d0a4f"
        ),
        .binaryTarget(
            name: "swresample",
            url: "https://github.com/nphil/stashy-videoengine/releases/download/v1.1.0/libswresample.xcframework.zip",
            checksum: "0974a2a88fe859d109476b0237dae5c33dade8998ff3eb4ee267cac256afbdb3"
        ),
        .target(
            name: "FFmpegSupport",
            dependencies: [
                "avutil", "avcodec", "avformat",
                "avfilter", "swscale", "swresample",
            ],
            linkerSettings: [
                .linkedLibrary("z"),
                .linkedLibrary("bz2"),
                .linkedLibrary("iconv"),
                .linkedLibrary("c++"),
                .linkedFramework("VideoToolbox"),
                .linkedFramework("CoreMedia"),
                .linkedFramework("CoreVideo"),
                .linkedFramework("CoreFoundation"),
                .linkedFramework("Security"),
                .linkedFramework("AudioToolbox"),
                .linkedFramework("Metal"),
            ]
        ),
    ]
)
