#!/usr/bin/env bash
# ===========================================================================
# gen-package-swift.sh <tag>
#
# Emits a Package.swift (to stdout) exposing the 6 xcframeworks as SwiftPM
# binary targets pinned to the GitHub Release assets for <tag>, plus a small
# FFmpegSupport target that carries the system-library / framework linker
# settings FFmpeg needs. Checksums are read from build/dist/checksums.txt.
# ===========================================================================
set -euo pipefail

TAG="${1:?usage: gen-package-swift.sh <tag>}"
REPO="${REPO:-nphil/stashy-videoengine}"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CHK="$ROOT/build/dist/checksums.txt"

# SwiftPM target name -> xcframework basename
LIBS=(avutil avcodec avformat avfilter swscale swresample)

checksum_for() {
  awk -v f="lib$1.xcframework.zip" '$2==f {print $1}' "$CHK"
}

emit_binary_targets() {
  local name sum
  for name in "${LIBS[@]}"; do
    sum="$(checksum_for "$name")"
    [ -n "$sum" ] || { echo "missing checksum for lib$name" >&2; exit 1; }
    cat <<EOF
        .binaryTarget(
            name: "$name",
            url: "https://github.com/$REPO/releases/download/$TAG/lib$name.xcframework.zip",
            checksum: "$sum"
        ),
EOF
  done
}

cat <<EOF
// swift-tools-version:5.9
// AUTO-GENERATED by scripts/gen-package-swift.sh for release $TAG.
// Do not edit by hand — re-run the release workflow to regenerate.
//
// Consumers import the individual modules (Libavformat, Libavcodec, Libavutil,
// Libavfilter, Libswscale, Libswresample). The clang module map lives inside
// the libavutil xcframework and declares all six modules.
import PackageDescription

let package = Package(
    name: "StashyVideoEngine",
    platforms: [.iOS(.v15)],
    products: [
        .library(
            name: "FFmpeg",
            targets: [
                "avutil", "avcodec", "avformat",
                "avfilter", "swscale", "swresample",
                "FFmpegSupport",
            ]
        ),
    ],
    targets: [
$(emit_binary_targets)
        .target(
            name: "FFmpegSupport",
            dependencies: [
                "avutil", "avcodec", "avformat",
                "avfilter", "swscale", "swresample",
            ],
            linkerSettings: [
                .linkedLibrary("z"),
                .linkedFramework("VideoToolbox"),
                .linkedFramework("CoreMedia"),
                .linkedFramework("CoreVideo"),
                .linkedFramework("CoreFoundation"),
            ]
        ),
    ]
)
EOF
